name: good_first_issue
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+4

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  colorize_lumberdash: ^3.0.0
  dartx: ^1.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.14
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  github_api:
    path: packages/github_api
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  html2md: ^1.2.6
  launch_review: ^3.0.1
  lumberdash: ^3.0.0
  meta: ^1.8.0
  riverpod: ^2.3.2
  share_plus: ^6.3.1
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  pedantic: ^1.8.0+1
  print_lumberdash: ^3.0.0
  remove_from_coverage: ^2.0.0
  test: ^1.21.7

dependency_overrides:
  win32: ^5.9.0

flutter:
  uses-material-design: true
